export const SAVE_VELOCITY_IN_LOCALSTORAGE = 'SAVE_VELOCITY_IN_LOCALSTORAGE'
export const UPDATE_VELOCITY = Symbol('UPDATE_VELOCITY')
export const UPDATE_WITH_ALEATORY_VELOCITY = Symbol('UPDATE_WITH_ALEATORY_VELOCITY')
export const UPLOAD_VELOCITY_FROM_LOCALSTORAGE = Symbol('UPLOAD_VELOCITY_FROM_LOCALSTORAGE')
